/**
 * English → Thai gloss for common MTG rules text and keywords.
 * Longer phrases are matched before shorter keys in translateOracleText.
 */
export const KEYWORD_THAI_MAP: Record<string, string> = {
  // Multi-word / phrase (longer first)
  "first strike": "โจมตีก่อน",
  "when": "เมื่อ",
  "double strike": "โจมตีก่อนสองครั้ง",
  "split second": "เสี้ยววินาที",
  "living weapon": "อาวุธมีชีวิต",
  "read ahead": "อ่านล่วงหน้า",
  "jump-start": "สตาร์ทกระโดด",
  "can't be countered": "ป้องกันไม่ได้",
  "can't block": "บล็อกไม่ได้",
  "can't attack": "โจมตีไม่ได้",
  "can't be blocked": "บล็อกไม่ได้",
  "except by creatures with flying or reach":
    "ยกเว้นโดยครีเจอร์ที่มีบินได้หรือแตะไกล",
  "activated abilities": "ความสามารถที่เปิดใช้",
  "triggered abilities": "ความสามารถที่สะสม",
  "mana abilities": "ความสามารถมานา",
  "enters the battlefield": "เข้าสนาม",
  "enters tapped": "เข้าสนามในโหมดแตะ",
  "dies": "ตาย",
  "is destroyed": "ถูกทำลาย",
  "is exiled": "ถูกเนรเทศ",
  "from your graveyard": "จากสุสานของคุณ",
  "from a graveyard": "จากสุสาน",
  "from exile": "จากโซนเนรเทศ",
  "from your library": "จากกองจั่วของคุณ",
  "from your hand": "จากมือของคุณ",
  "from the battlefield": "จากสนาม",
  "at the beginning of": "เมื่อเริ่ม",
  "at end of combat": "เมื่อจบการต่อสู้",
  "during your turn": "ในเทิร์นของคุณ",
  "each opponent": "คู่ต่อสู้แต่ละคน",
  "each creature": "ครีเจอร์แต่ละตัว",
  "target creature": "ครีเจอร์เป้าหมาย",
  "target player": "ผู้เล่นเป้าหมาย",
  "target permanent": "ถาวรวัตถุเป้าหมาย",
  "any target": "เป้าหมายใดๆ",
  "you may": "คุณอาจ",
  "you control": "ที่คุณควบคุม",
  "you don't control": "ที่คุณไม่ควบคุม",
  "another target": "เป้าหมายอื่น",
  "choose one": "เลือกหนึ่งอย่าง",
  "choose two": "เลือกสองอย่าง",
  "counter target spell": "ต้านคาถาเป้าหมาย",
  "draw a card": "จั่วการ์ดหนึ่งใบ",
  "draw two cards": "จั่วการ์ดสองใบ",
  "discard a card": "ทิ้งการ์ดหนึ่งใบ",
  "a creature": "ครีเจอร์หนึ่งตัว",
  "an artifact": "Artifact หนึ่งชิ้น",
  "an enchantment": "หนึ่ง Enchantment",
  "a land": "ดินแดนหนึ่งใบ",
  "a token": "โทเค็นหนึ่งตัว",
  "a player": "ผู้เล่นหนึ่งคน",
  "mill": "ส่งจากกองจั่วไปสุสาน",
  "mill two cards": "ส่งการ์ดสองใบจากกองจั่วไปสุสาน",
  "mill three cards": "ส่งการ์ดสามใบจากกองจั่วไปสุสาน",
  "gain life": "ได้รับพลังชีวิต",
  "lose life": "สูญเสียพลังชีวิต",
  "deal damage": "สร้างความเสียหาย",
  "deals damage": "สร้างความเสียหาย",
  "dealt damage": "ความเสียหายที่ได้รับ",

  // Zones & movement
  "search your library": "ค้นหากองจั่วของคุณ",
  "shuffle your library": "สับกองจั่วของคุณ",
  "put onto the battlefield": "วางลงสนาม",
  "put into your graveyard": "ใส่ลงสุสานของคุณ",
  "put into the graveyard": "ใส่ลงสุสาน",
  "put into your hand": "ใส่ในมือของคุณ",
  "return to your hand": "คืนมือของคุณ",
  "return to the battlefield": "คืนสนาม",
  "return to its owner's hand": "คืนมือเจ้าของ",
  "top of your library": "บนสุดกองจั่วของคุณ",
  "bottom of your library": "ล่างสุดกองจั่วของคุณ",
  "on the battlefield": "บนสนาม",
  "in your hand": "ในมือของคุณ",
  "in your graveyard": "ในสุสานของคุณ",
  "in your library": "ในกองจั่วของคุณ",
  "in exile": "ในโซนเนรเทศ",
  "the command zone": "โซนบัญชาการ",
  "command zone": "โซนบัญชาการ",
  "the stack": "สแต็ก",
  "the battlefield": "สนาม",
  "the graveyard": "สุสาน",

  // Phases & steps
  "the beginning of your upkeep": "เริ่มอัพคีพของคุณ",
  "the beginning of your end step": "เริ่มช่วงจบของคุณ",
  "the beginning of your draw step": "เริ่มช่วงจั่วของคุณ",
  "at the beginning of combat": "เมื่อเริ่มการต่อสู้",
  "beginning of combat": "เริ่มการต่อสู้",
  "precombat main phase": "เฟสหลักก่อนต่อสู้",
  "postcombat main phase": "เฟสหลักหลังต่อสู้",
  "declare attackers": "ประกาศผู้โจมตี",
  "declare blockers": "ประกาศผู้บล็อก",
  "your upkeep": "อัพคีพของคุณ",
  "your draw step": "ช่วงจั่วของคุณ",
  "your end step": "ช่วงจบของคุณ",
  "your main phase": "เฟสหลักของคุณ",
  "your next upkeep": "อัพคีพถัดไปของคุณ",
  "combat phase": "เฟสต่อสู้",
  "main phase": "เฟสหลัก",
  "end step": "ช่วงจบ",
  "upkeep step": "ช่วงอัพคีพ",
  "draw step": "ช่วงจั่ว",

  // Casting & costs
  "cast this spell": "ร่ายคาถานี้",
  "when you cast this spell": "เมื่อคุณร่ายคาถานี้",
  "whenever you cast": "เมื่อใดก็ตามที่คุณร่าย",
  "without paying its mana cost": "โดยไม่ต้องจ่ายค่ามานา",
  "as an additional cost": "เป็นค่าใช้จ่ายเพิ่มเติม",
  "mana value": "ค่ามานา",
  "mana cost": "ค่ามานา",
  "converted mana cost": "ค่ามานาแปลง",
  "of any color": "สีใดก็ได้",
  "add one mana": "เพิ่มมานาหนึ่ง",
  "add mana": "เพิ่มมานา",

  // Targeting & selection
  "target creature or player": "ครีเจอร์หรือผู้เล่นเป้าหมาย",
  "target creature or planeswalker": "ครีเจอร์หรือเพลนส์วอล์คเกอร์เป้าหมาย",
  "target artifact or enchantment": "Artifact หรือ Enchantment เป้าหมาย",
  "target nonland permanent": "ถาวรวัตถุที่ไม่ใช่ดินแดนเป้าหมาย",
  "target noncreature permanent": "ถาวรวัตถุที่ไม่ใช่ครีเจอร์เป้าหมาย",
  "target opponent": "ฝ่ายตรงข้ามเป้าหมาย",
  "target spell": "คาถาเป้าหมาย",
  "exile target": "เนรเทศเป้าหมาย",
  "destroy target": "ทำลายเป้าหมาย",
  "return target": "คืนเป้าหมาย",
  "up to one": "ได้ถึงหนึ่ง",
  "up to two": "ได้ถึงสอง",
  "up to three": "ได้ถึงสาม",
  "up to": "ได้ถึง",
  "one or more": "หนึ่งหรือมากกว่า",
  "or more": "หรือมากกว่า",
  "or less": "หรือน้อยกว่า",

  // Creatures & combat
  "creatures you control": "ครีเจอร์ที่คุณควบคุม",
  "creature you control": "ครีเจอร์ที่คุณควบคุม",
  "permanent you control": "ถาวรวัตถุที่คุณควบคุม",
  "permanents you control": "ถาวรวัตถุที่คุณควบคุม",
  "creatures you don't control": "ครีเจอร์ที่คุณไม่ควบคุม",
  "under your control": "ภายใต้การควบคุมของคุณ",
  "all creatures": "ครีเจอร์ทั้งหมด",
  "each creature you control": "ครีเจอร์แต่ละตัวที่คุณควบคุม",
  "nontoken creature": "ครีเจอร์ที่ไม่ใช่โทเค็น",
  "nonland permanent": "ถาวรวัตถุที่ไม่ใช่ดินแดน",
  "nonbasic land": "ดินแดนไม่พื้นฐาน",
  "attacks or blocks": "โจมตีหรือบล็อก",
  "attacks alone": "โจมตีคนเดียว",
  "attacks and isn't blocked": "โจมตีและไม่ถูกบล็อก",
  "whenever a creature": "เมื่อใดก็ตามที่ครีเจอร์",
  "whenever this creature": "เมื่อใดก็ตามที่ครีเจอร์ตัวนี้",
  "when this creature dies": "เมื่อครีเจอร์ตัวนี้ตาย",
  "this creature": "ครีเจอร์ตัวนี้",
  "that creature": "ครีเจอร์ตัวนั้น",

  // Counters
  "put a +1/+1 counter": "วางเคาน์เตอร์ +1/+1",
  "put a -1/-1 counter": "วางเคาน์เตอร์ -1/-1",
  "+1/+1 counter": "เคาน์เตอร์ +1/+1",
  "-1/-1 counter": "เคาน์เตอร์ -1/-1",
  "+1/+1 counters": "เคาน์เตอร์ +1/+1",
  "-1/-1 counters": "เคาน์เตอร์ -1/-1",
  "loyalty counter": "เคาน์เตอร์ความจงรักภักดี",
  "loyalty counters": "เคาน์เตอร์ความจงรักภักดี",

  // Token types
  "treasure token": "โทเค็นสมบัติ",
  "treasure tokens": "โทเค็นสมบัติ",
  "food token": "โทเค็นอาหาร",
  "food tokens": "โทเค็นอาหาร",
  "clue token": "โทเค็นเบาะแส",
  "clue tokens": "โทเค็นเบาะแส",
  "blood token": "โทเค็นเลือด",
  "blood tokens": "โทเค็นเลือด",
  "creature token": "โทเค็นครีเจอร์",
  "artifact token": "โทเค็น Artifact",
  "create a token": "สร้างโทเค็น",
  "create a copy": "สร้างสำเนา",

  // Spell types
  "instant or sorcery": "Instant หรือ Sorcery",
  "instant or sorcery card": "การ์ด Instant หรือ Sorcery",
  "noncreature spell": "คาถาที่ไม่ใช่ครีเจอร์",
  "creature spell": "คาถาครีเจอร์",
  "creature card": "การ์ดครีเจอร์",
  "artifact card": "การ์ด Artifact",
  "enchantment card": "การ์ด Enchantment",
  "land card": "การ์ดดินแดน",

  // Common oracle text patterns
  "look at the top": "ดูการ์ดบนสุด",
  "reveal the top": "เปิดการ์ดบนสุด",
  "each player": "ผู้เล่นแต่ละคน",
  "each turn": "แต่ละเทิร์น",
  "this turn": "เทิร์นนี้",
  "for each": "สำหรับแต่ละ",
  "this spell": "คาถานี้",
  "this card": "การ์ดใบนี้",
  "that card": "การ์ดใบนั้น",
  "that player": "ผู้เล่นคนนั้น",
  "its controller": "ผู้ควบคุมของมัน",
  "its owner": "เจ้าของของมัน",
  "if you do": "ถ้าคุณทำ",
  "if you don't": "ถ้าคุณไม่ทำ",
  "rather than": "แทนที่จะ",
  "in addition to": "นอกเหนือจาก",
  "at random": "แบบสุ่ม",
  "face down": "คว่ำหน้า",
  "face up": "หงายหน้า",
  "an opponent": "ฝ่ายตรงข้ามหนึ่งคน",
  "an opponent controls": "ที่ฝ่ายตรงข้ามควบคุม",
  "your opponents": "ฝ่ายตรงข้ามของคุณ",
  "with flying": "ที่มีบินได้",
  "without flying": "ที่ไม่มีบินได้",
  "gains flying": "ได้รับความสามารถบิน",
  "gains haste": "ได้รับความสามารถเร่ง",
  "gains trample": "ได้รับความสามารถเหยียบ",
  "gets +1/+1": "ได้รับ +1/+1",
  "gets +2/+2": "ได้รับ +2/+2",
  "gets -1/-1": "ได้รับ -1/-1",
  "gets -2/-2": "ได้รับ -2/-2",
  "destroy all creatures": "ทำลายครีเจอร์ทั้งหมด",
  "exile all": "เนรเทศทั้งหมด",
  "each of those": "แต่ละตัว",
  "copy of": "สำเนาของ",

  "equal to": "เท่ากับ",
  "until end of turn": "จนจบเทิร์น",
  "until your next turn": "จนถึงเทิร์นถัดไปของคุณ",
  "end of turn": "จบเทิร์น",
  "combat damage": "ความเสียหายจากการต่อสู้",
  "noncombat damage": "ความเสียหายนอกการต่อสู้",
  "power and toughness": "พลังโจมตีและพลังป้องกัน",
  "power": "พลังโจมตี",
  "toughness": "พลังป้องกัน",
  "token": "โทเค็น",
  "tokens": "โทเค็น",
  "sacrifice": "สังเวย",
  "tap": "แตะ",
  "untap": "แตะกลับ",
  "tapped": "แตะแล้ว",
  "untapped": "ยังไม่แตะ",
  "legendary": "ตำนาน",
  "basic land": "ดินแดนพื้นฐาน",
  "creature": "ครีเจอร์",
  "artifact": "Artifact",
  "enchantment": "Enchantment",
  "instant": "Instant",
  "sorcery": "Sorcery",
  "planeswalker": "เพลนส์วอล์คเกอร์",
  "battle": "การรบ",
  "land": "ดินแดน",
  "aura": "ออร่า",
  "equipment": "อุปกรณ์",
  "vehicle": "ยานพาหนะ",
  "saga": "สะกา",

  // Keyword abilities (single word / short)
  flying: "Flying",
  reach: "Reach",
  trample: "Trample",
  lifelink: "Lifelink",
  deathtouch: "Deathtouch",
  vigilance: "Vigilance",
  haste: "Haste",
  menace: "Menace",
  indestructible: "Indestructible",
  hexproof: "Hexproof",
  shroud: "Shroud",
  ward: "Ward",
  flash: "Flash",
  defender: "Defender",
  prowess: "Prowess",
  intimidate: "Intimidate",
  skulk: "Skulk",
  cascade: "Cascade",
  convoke: "Convoke",
  delve: "Delve",
  affinity: "Affinity",
  kicker: "Kicker",
  multikicker: "Multikicker",
  flashback: "Flashback",
  madness: "Madness",
  morph: "Morph",
  megamorph: "Megamorph",
  manifest: "Manifest",
  bolster: "Bolster",
  exploit: "Exploit",
  renown: "Renown",
  melee: "Melee",
  crew: "Crew",
  fabricate: "Fabricate",
  partner: "Partner",
  improvise: "Improvise",
  embalm: "Embalm",
  eternalize: "Eternalize",
  mentor: "Mentor",
  riot: "Riot",
  spectacle: "Spectacle",
  escape: "Escape",
  companion: "Companion",
  mutate: "Mutate",
  foretell: "Foretell",
  disturb: "Disturb",
  training: "Training",
  toxic: "Toxic",
  backup: "Backup",
  reconfigure: "Reconfigure",
  storm: "Storm",
  suspend: "Suspend",
  undying: "Undying",
  unleash: "Unleash",
  evolve: "Evolve",
  extort: "Extort",
  fuse: "Fuse",
  tribute: "Tribute",
  dethrone: "Dethrone",
  annihilator: "Annihilator",
  changeling: "Changeling",
  banding: "Banding",
  flanking: "Flanking",
  phasing: "Phasing",
  shadow: "Shadow",
  horsemanship: "Horsemanship",
  protection: "Protection",
  regenerate: "Regenerate",
  soulbond: "Soulbond",
  undaunted: "Undaunted",
};
