/**
 * English → Thai gloss for common MTG rules text and keywords.
 * Longer phrases are matched before shorter keys in translateOracleText.
 */
export const KEYWORD_THAI_MAP: Record<string, string> = {
  // Multi-word / phrase (longer first)
  "first strike": "โจมตีก่อน",
  "double strike": "โจมตีก่อนสองครั้ง",
  "split second": "เสี้ยววินาที",
  "living weapon": "อาวุธมีชีวิต",
  "read ahead": "อ่านล่วงหน้า",
  "jump-start": "สตาร์ทกระโดด",
  "can't be countered": "ป้องกันไม่ได้",
  "can't block": "บล็อกไม่ได้",
  "can't attack": "โจมตีไม่ได้",
  "can't be blocked": "บล็อกไม่ได้",
  "except by creatures with flying or reach":
    "ยกเว้นโดยครีเจอร์ที่มีบินได้หรือแตะไกล",
  "activated abilities": "ความสามารถที่เปิดใช้",
  "triggered abilities": "ความสามารถที่สะสม",
  "mana abilities": "ความสามารถมานา",
  "enters the battlefield": "เข้าสนาม",
  "enters tapped": "เข้าสนามในโหมดแตะ",
  "dies": "ตาย",
  "is destroyed": "ถูกทำลาย",
  "is exiled": "ถูกเนรเทศ",
  "from your graveyard": "จากสุสานของคุณ",
  "from a graveyard": "จากสุสาน",
  "from exile": "จากโซนเนรเทศ",
  "from your library": "จากไลบรารีของคุณ",
  "from your hand": "จากมือของคุณ",
  "from the battlefield": "จากสนาม",
  "at the beginning of": "เมื่อเริ่ม",
  "at end of combat": "เมื่อจบการต่อสู้",
  "during your turn": "ในเทิร์นของคุณ",
  "each opponent": "คู่ต่อสู้แต่ละคน",
  "each creature": "ครีเจอร์แต่ละตัว",
  "target creature": "ครีเจอร์เป้าหมาย",
  "target player": "ผู้เล่นเป้าหมาย",
  "target permanent": "ถาวรวัตถุเป้าหมาย",
  "any target": "เป้าหมายใดๆ",
  "you may": "คุณอาจ",
  "you control": "ที่คุณควบคุม",
  "you don't control": "ที่คุณไม่ควบคุม",
  "another target": "เป้าหมายอื่น",
  "choose one": "เลือกหนึ่งอย่าง",
  "choose two": "เลือกสองอย่าง",
  "counter target spell": "ต้านคาถาเป้าหมาย",
  "draw a card": "จั่วการ์ดหนึ่งใบ",
  "draw two cards": "จั่วการ์ดสองใบ",
  "discard a card": "ทิ้งการ์ดหนึ่งใบ",
  "mill": "ส่งจากไลบรารีไปสุสาน",
  "mill two cards": "ส่งการ์ดสองใบจากไลบรารีไปสุสาน",
  "mill three cards": "ส่งการ์ดสามใบจากไลบรารีไปสุสาน",
  "gain life": "ได้รับพลังชีวิต",
  "lose life": "สูญเสียพลังชีวิต",
  "deal damage": "สร้างความเสียหาย",
  "deals damage": "สร้างความเสียหาย",
  "dealt damage": "ความเสียหายที่ได้รับ",
  "equal to": "เท่ากับ",
  "until end of turn": "จนจบเทิร์น",
  "until your next turn": "จนถึงเทิร์นถัดไปของคุณ",
  "end of turn": "จบเทิร์น",
  "combat damage": "ความเสียหายจากการต่อสู้",
  "noncombat damage": "ความเสียหายนอกการต่อสู้",
  "power and toughness": "พลังโจมตีและพลังป้องกัน",
  "power": "พลังโจมตี",
  "toughness": "พลังป้องกัน",
  "token": "โทเค็น",
  "tokens": "โทเค็น",
  "sacrifice": "สังเวย",
  "tap": "แตะ",
  "untap": "แตะกลับ",
  "tapped": "แตะแล้ว",
  "untapped": "ยังไม่แตะ",
  "legendary": "ตำนาน",
  "basic land": "ดินแดนพื้นฐาน",
  "creature": "ครีเจอร์",
  "artifact": "สิ่งประดิษฐ์",
  "enchantment": "มนต์เสริม",
  "instant": "คาถาฉับพลัน",
  "sorcery": "คาถา",
  "planeswalker": "เพลนส์วอล์คเกอร์",
  "battle": "การรบ",
  "land": "ดินแดน",
  "aura": "ออร่า",
  "equipment": "อุปกรณ์",
  "vehicle": "ยานพาหนะ",
  "saga": "สะกา",

  // Keyword abilities (single word / short)
  flying: "บินได้",
  reach: "แตะไกล",
  trample: "เหยียบย่ำ",
  lifelink: "สายโลหิต",
  deathtouch: "สัมผัสมรณะ",
  vigilance: "ความระวังภัย",
  haste: "รวดเร็ว",
  menace: "ข่มขู่",
  indestructible: "ทำลายไม่ได้",
  hexproof: "ป้องกันคาถา",
  shroud: "คลุมกาย",
  ward: "ป้องกัน",
  flash: "แฟลช",
  defender: "ป้องกันเท่านั้น",
  prowess: "ฝีมือ",
  intimidate: "ข่มขวัญ",
  skulk: "หลบซ่อน",
  cascade: "คาสเคด",
  convoke: "เรียกชุมนุม",
  delve: "เจาะลึก",
  affinity: "สนิทสนม",
  kicker: "เตะเสริม",
  multikicker: "เตะเสริมหลายครั้ง",
  flashback: "ย้อนอดีต",
  madness: "คลั่ง",
  morph: "เปลี่ยนร่างลับ",
  megamorph: "เมกามอร์ฟ",
  manifest: "ปรากฏ",
  bolster: "เสริมกำลัง",
  exploit: "ใช้ประโยชน์",
  renown: "ชื่อเสียง",
  melee: "ประชิด",
  crew: "ลูกเรือ",
  fabricate: "ประดิษฐ์",
  partner: "หุ้นส่วน",
  improvise: "ใช้ของแทนมานา",
  embalm: "มัมมี่",
  eternalize: "นิรันดร์",
  mentor: "พี่เลี้ยง",
  riot: "จลาจล",
  spectacle: "การแสดง",
  escape: "หลบหนี",
  companion: "เพื่อนร่วมทาง",
  mutate: "กลายพันธุ์",
  foretell: "พยากรณ์",
  disturb: "รบกวน",
  training: "ฝึกฝน",
  toxic: "พิษร้าย",
  backup: "สำรอง",
  reconfigure: "ปรับแต่ง",
  storm: "พายุ",
  suspend: "ระงับ",
  undying: "เป็นอมตะ",
  unleash: "ปลดปล่อย",
  evolve: "วิวัฒน์",
  extort: "รีดไถ",
  fuse: "ฟิวส์",
  tribute: "สังเวย",
  dethrone: "โค่นบัลลังก์",
  annihilator: "ผู้ทำลายล้าง",
  changeling: "เปลี่ยนร่าง",
  banding: "รวมกลุ่ม",
  flanking: "โจมตีข้าง",
  phasing: "เฟส",
  shadow: "เงา",
  horsemanship: "ขี่ม้า",
  protection: "ป้องกัน",
  regenerate: "ฟื้นฟู",
  soulbond: "ผูกวิญญาณ",
  undaunted: "ไม่หวั่นไหว",
};
